---
- hosts: kubernetes-master-node 
  vars_files:
  - ../env_variables

  tasks:
  - name: Pulling images required for setting up a Kubernetes cluster
    shell: sudo kubeadm config images pull

  - name: Resetting kubeadm
    shell: sudo kubeadm reset -f
    register: output

  - name: Initializing Kubernetes cluster
    shell: sudo kubeadm init --apiserver-advertise-address {{ cluster_adr }}
    register: output

  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest=/home/{{user}}/{{ token_file }}

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config


  - name: Installing Weavenet Network Addon
    shell: |
     kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
    when: POD_NETWORK == "weavenet"
    register: result
    retries: 3
    delay: 10
    until: result.rc == 0
    ignore_errors: yes

