- hosts: all
  vars_files:
    - ../env_variables 
  tasks:

    #- name: Add Hostname to /etc/hosts
    #  become: yes
    #  shell: grep -q 'k8s' /etc/hosts && echo exists || echo "{{ansible_host}} {{ansible_hostname}}" >> /etc/hosts
    #  register: result
    #  changed_when: result.stdout.find('exists') == -1

    - name: Installing Dependencies (CentOS)
      become: yes
      yum:
        name: [yum-utils, device-mapper-persistent-data, lvm2, wget]
        state: latest

    - name: Creating a repository file for Kubernetes (CentOS)
      become: yes
      file:
        path: /etc/yum.repos.d/kubernetes.repo
        state: touch

    - name: Adding repository details in Kubernetes repo file (CentOS)
      become: yes
      blockinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        block: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  


    - name: Installing Docker
      become: yes
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        chmod +x get-docker.sh
        ./get-docker.sh

    - name: Installing Container SELinux (CentOS)
      become: yes
      yum:
        name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-1.el7_6.noarch.rpm
        state: present
      

    - name: Changing docker default cgroup.
      become: yes
      shell: |
        mkdir -p /etc/docker
        cat << EOF |  tee /etc/docker/daemon.json
        {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
        "max-size": "100m"
           },
        "storage-driver": "overlay2"
        }
        EOF


    - name: Create Docker proxy service file
      become: yes
      shell: |
        mkdir -p /etc/systemd/system/docker.service.d
    - name: Copying docker proxy conf
      become: yes
      copy:
        src: "/home/{{user}}/docker-proxy.conf"
        dest : "/etc/systemd/system/docker.service.d/http-proxy.conf"
        follow: yes

    - name: Restarting Docker service
      become: yes
      shell: |
        systemctl daemon-reload
        systemctl restart docker

    - name: Installing Kubernetes (CentOS)
      become: yes
      yum:
        name: "{{ packages }}"
        state: present 
        update_cache: yes
      vars:
        packages:
        - kubectl-{{ CENTOS_K8S_VERSION }}
        - kubeadm-{{ CENTOS_K8S_VERSION }}
        - kubelet-{{ CENTOS_K8S_VERSION }}


    - name: Starting and Enabling docker service
      become: yes
      service:
        name: docker
        state: started
        enabled: yes

    - name: Starting and Enabling Kubelet service
      become: yes
      service:
        name: kubelet
        state: started
        enabled: yes