- hosts: all
  vars_files:
    - ../env_variables 
  tasks:

    - name: Changing hostnames
      become: yes
      shell:  hostnamectl set-hostname {{ansible_hostname}}

    - name: Add Hostname to /etc/hosts
      become: yes
      shell: grep -q 'k8s' /etc/hosts && echo exists || echo "{{ansible_host}} {{ansible_hostname}}" >> /etc/hosts
      register: result
      changed_when: result.stdout.find('exists') == -1

    - name: Installing Dependencies (Ubuntu)
      become: yes
      apt:
        name: [curl, wget, lvm2]
        state: latest
      environment: "{{ proxy_env }}"


    - name: Creating a repository file for Kubernetes (Ubuntu)
      become: yes
      file:
       path: /etc/apt/sources.list.d/kubernetes.list
       state: touch

    - name: Adding Kubernetes repository gpg key (Ubuntu)
      become: yes
      shell: |
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      environment: "{{ proxy_env }}"

    - name: Adding repository details in Kubernetes repo file  (Ubuntu)
      become: yes
      blockinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        block: |
          deb https://apt.kubernetes.io/ kubernetes-xenial main


    - name: Installing Docker
      become: yes
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        chmod +x get-docker.sh
        ./get-docker.sh
      environment: "{{ proxy_env }}"

      

    - name: Changing docker defaul cgroup.
      become: yes
      shell: |
        mkdir -p /etc/docker
        cat << EOF |  tee /etc/docker/daemon.json
        {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
        "max-size": "100m"
           },
        "storage-driver": "overlay2"
        }
        EOF
    - name: Adding Docker to $USER Group
      become: yes
      shell: |
        groupadd docker
        usermod -aG docker {{user}}
        systemctl daemon-reload
      ignore_errors: yes

    - name: Create Docker proxy service file
      become: yes
      shell: |
        mkdir -p /etc/systemd/system/docker.service.d
    - name: Copying docker proxy conf
      become: yes
      copy:
        src: "/home/{{user}}/docker-proxy.conf"
        dest : "/etc/systemd/system/docker.service.d/http-proxy.conf"
        follow: yes

    - name: Restarting Docker service
      become: yes
      shell: |
        systemctl daemon-reload
        systemctl restart docker

    - name: Installing Kubernetes (Ubuntu)
      become: yes
      apt:
        name: "{{ packages }}"
        state: present 
        update_cache: yes
      vars:
        packages:
        - kubectl={{ UBUNTU_K8S_VERSION }}
        - kubeadm={{ UBUNTU_K8S_VERSION }}
        - kubelet={{ UBUNTU_K8S_VERSION }}
      environment: "{{ proxy_env }}"

    - name: Prevent kubeadm, kubectl, kubelet from upgrading
      become: yes
      shell:  apt-mark hold kubelet kubeadm kubectl
      when: ansible_os_family == "Debian"
      environment: "{{ proxy_env }}"


    - name: Starting and Enabling docker service
      become: yes
      service:
        name: docker
        state: started
        enabled: yes

    - name: Starting and Enabling Kubelet service
      become: yes
      service:
        name: kubelet
        state: started
        enabled: yes